##############
### base
##############

server:
  port: 8080
  forward-headers-strategy: framework
  
spring:
  application:
    name: apidoc
  profiles:
    active: local
  main:
      banner-mode: 'off'
